### ISSUE TITLE
Update redis to new version

### ISSUE THREAD

**Issue by FranCoFeliz** [mperham/sidekiq.cr#84]
While trying to run shards install, after adding sidekiq dependency, the console shows this message:
`Error resolving redis (~> 1.8.0, ~> 2.0)`

Redis dependency now shows another version, and the issue disapears by removing sidekiq's lines.

```
dependencies:
  redis:
    github: stefanwille/crystal-redis
    version: ~> 2.5.3
```
Current: 
```
dependencies:
  redis:
    github: stefanwille/crystal-redis
    version: ~> 2.0
```

Thanks!
